-- CreateTable
CREATE TABLE "USER" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "TELEGRAM_ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DATA_CRIACAO" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "TREINO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "USER_ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DATA_CRIACAO" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TREINO_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "EXERCICIO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "NOME" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "TREINO_EXERCICIO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "TREINO_ID" TEXT NOT NULL,
    "EXERCICIO_ID" TEXT NOT NULL,
    "ORDEM" INTEGER NOT NULL,
    CONSTRAINT "TREINO_EXERCICIO_TREINO_ID_fkey" FOREIGN KEY ("TREINO_ID") REFERENCES "TREINO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TREINO_EXERCICIO_EXERCICIO_ID_fkey" FOREIGN KEY ("EXERCICIO_ID") REFERENCES "EXERCICIO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "SESSAO_TREINO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "TREINO_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "INICIADO_EM" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FINALIZADO_EM" DATETIME,
    CONSTRAINT "SESSAO_TREINO_TREINO_ID_fkey" FOREIGN KEY ("TREINO_ID") REFERENCES "TREINO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SESSAO_TREINO_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "EXECUCAO_EXERCICIO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "SESSAO_TREINO_ID" TEXT NOT NULL,
    "EXERCICIO_ID" TEXT NOT NULL,
    "PESO" REAL NOT NULL,
    "REPETICOES" INTEGER NOT NULL,
    CONSTRAINT "EXECUCAO_EXERCICIO_SESSAO_TREINO_ID_fkey" FOREIGN KEY ("SESSAO_TREINO_ID") REFERENCES "SESSAO_TREINO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EXECUCAO_EXERCICIO_EXERCICIO_ID_fkey" FOREIGN KEY ("EXERCICIO_ID") REFERENCES "EXERCICIO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_TELEGRAM_ID_key" ON "USER"("TELEGRAM_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TREINO_EXERCICIO_TREINO_ID_EXERCICIO_ID_key" ON "TREINO_EXERCICIO"("TREINO_ID", "EXERCICIO_ID");
