/*
  Warnings:

  - A unique constraint covering the columns `[TREINO_ID,ORDEM]` on the table `TREINO_EXERCICIO` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `EXERCICIO_ATUAL_ID` to the `SESSAO_TREINO` table without a default value. This is not possible if the table is not empty.

*/
-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_EXECUCAO_EXERCICIO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "SESSAO_TREINO_ID" TEXT NOT NULL,
    "EXERCICIO_ID" TEXT NOT NULL,
    "PESO" REAL NOT NULL,
    "REPETICOES" INTEGER NOT NULL,
    "ATUALIZADO_EM" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "EXECUCAO_EXERCICIO_SESSAO_TREINO_ID_fkey" FOREIGN KEY ("SESSAO_TREINO_ID") REFERENCES "SESSAO_TREINO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "EXECUCAO_EXERCICIO_EXERCICIO_ID_fkey" FOREIGN KEY ("EXERCICIO_ID") REFERENCES "EXERCICIO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_EXECUCAO_EXERCICIO" ("EXERCICIO_ID", "ID", "PESO", "REPETICOES", "SESSAO_TREINO_ID") SELECT "EXERCICIO_ID", "ID", "PESO", "REPETICOES", "SESSAO_TREINO_ID" FROM "EXECUCAO_EXERCICIO";
DROP TABLE "EXECUCAO_EXERCICIO";
ALTER TABLE "new_EXECUCAO_EXERCICIO" RENAME TO "EXECUCAO_EXERCICIO";
CREATE UNIQUE INDEX "EXECUCAO_EXERCICIO_SESSAO_TREINO_ID_EXERCICIO_ID_key" ON "EXECUCAO_EXERCICIO"("SESSAO_TREINO_ID", "EXERCICIO_ID");
CREATE TABLE "new_SESSAO_TREINO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "TREINO_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "EXERCICIO_ATUAL_ID" TEXT NOT NULL,
    "INICIADO_EM" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FINALIZADO_EM" DATETIME,
    CONSTRAINT "SESSAO_TREINO_TREINO_ID_fkey" FOREIGN KEY ("TREINO_ID") REFERENCES "TREINO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SESSAO_TREINO_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "SESSAO_TREINO_EXERCICIO_ATUAL_ID_fkey" FOREIGN KEY ("EXERCICIO_ATUAL_ID") REFERENCES "EXERCICIO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_SESSAO_TREINO" ("FINALIZADO_EM", "ID", "INICIADO_EM", "TREINO_ID", "USER_ID") SELECT "FINALIZADO_EM", "ID", "INICIADO_EM", "TREINO_ID", "USER_ID" FROM "SESSAO_TREINO";
DROP TABLE "SESSAO_TREINO";
ALTER TABLE "new_SESSAO_TREINO" RENAME TO "SESSAO_TREINO";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "TREINO_EXERCICIO_TREINO_ID_ORDEM_key" ON "TREINO_EXERCICIO"("TREINO_ID", "ORDEM");
