-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "USER" (
    "ID" TEXT NOT NULL,
    "TELEGRAM_ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DATA_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TREINO" (
    "ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DATA_CRIACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREINO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EXERCICIO" (
    "ID" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,

    CONSTRAINT "EXERCICIO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TREINO_EXERCICIO" (
    "ID" TEXT NOT NULL,
    "TREINO_ID" TEXT NOT NULL,
    "EXERCICIO_ID" TEXT NOT NULL,
    "ORDEM" INTEGER NOT NULL,

    CONSTRAINT "TREINO_EXERCICIO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SESSAO_TREINO" (
    "ID" TEXT NOT NULL,
    "TREINO_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "EXERCICIO_ATUAL_ID" TEXT NOT NULL,
    "INICIADO_EM" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FINALIZADO_EM" TIMESTAMP(3),

    CONSTRAINT "SESSAO_TREINO_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EXECUCAO_EXERCICIO" (
    "ID" TEXT NOT NULL,
    "SESSAO_TREINO_ID" TEXT NOT NULL,
    "EXERCICIO_ID" TEXT NOT NULL,
    "PESO" DOUBLE PRECISION NOT NULL,
    "REPETICOES" INTEGER NOT NULL,
    "ATUALIZADO_EM" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "EXECUCAO_EXERCICIO_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_TELEGRAM_ID_key" ON "USER"("TELEGRAM_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TREINO_EXERCICIO_TREINO_ID_EXERCICIO_ID_key" ON "TREINO_EXERCICIO"("TREINO_ID", "EXERCICIO_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TREINO_EXERCICIO_TREINO_ID_ORDEM_key" ON "TREINO_EXERCICIO"("TREINO_ID", "ORDEM");

-- CreateIndex
CREATE UNIQUE INDEX "EXECUCAO_EXERCICIO_SESSAO_TREINO_ID_EXERCICIO_ID_key" ON "EXECUCAO_EXERCICIO"("SESSAO_TREINO_ID", "EXERCICIO_ID");

-- Keep only one active workout session per user.
CREATE UNIQUE INDEX "SESSAO_TREINO_ONE_ACTIVE_PER_USER"
ON "SESSAO_TREINO" ("USER_ID")
WHERE "FINALIZADO_EM" IS NULL;

-- AddForeignKey
ALTER TABLE "TREINO" ADD CONSTRAINT "TREINO_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREINO_EXERCICIO" ADD CONSTRAINT "TREINO_EXERCICIO_TREINO_ID_fkey" FOREIGN KEY ("TREINO_ID") REFERENCES "TREINO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREINO_EXERCICIO" ADD CONSTRAINT "TREINO_EXERCICIO_EXERCICIO_ID_fkey" FOREIGN KEY ("EXERCICIO_ID") REFERENCES "EXERCICIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSAO_TREINO" ADD CONSTRAINT "SESSAO_TREINO_TREINO_ID_fkey" FOREIGN KEY ("TREINO_ID") REFERENCES "TREINO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSAO_TREINO" ADD CONSTRAINT "SESSAO_TREINO_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SESSAO_TREINO" ADD CONSTRAINT "SESSAO_TREINO_EXERCICIO_ATUAL_ID_fkey" FOREIGN KEY ("EXERCICIO_ATUAL_ID") REFERENCES "EXERCICIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXECUCAO_EXERCICIO" ADD CONSTRAINT "EXECUCAO_EXERCICIO_SESSAO_TREINO_ID_fkey" FOREIGN KEY ("SESSAO_TREINO_ID") REFERENCES "SESSAO_TREINO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXECUCAO_EXERCICIO" ADD CONSTRAINT "EXECUCAO_EXERCICIO_EXERCICIO_ID_fkey" FOREIGN KEY ("EXERCICIO_ID") REFERENCES "EXERCICIO"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
